package com.blackend.passwordmanager.others

import com.blackend.passwordmanager.R

object SiteMappings {

    val siteMap = mapOf(
        "adobe" to R.drawable.adobe,
        "airbnb" to R.drawable.airbnb,
        "amazon" to R.drawable.amazon,
        "apple" to R.drawable.apple,
        "bank" to R.drawable.bank,
        "behance" to R.drawable.behance,
        "discord" to R.drawable.discord,
        "dribbble" to R.drawable.dribbble,
        "evernote" to R.drawable.evernote,
        "fb" to R.drawable.facebook,
        "facebook" to R.drawable.facebook,
        "flipkart" to R.drawable.flipkart,
        "github" to R.drawable.github,
        "gitlab" to R.drawable.gitlab,
        "gmail" to R.drawable.google,
        "google" to R.drawable.google,
        "insta" to R.drawable.instagram,
        "instagram" to R.drawable.instagram,
        "line" to R.drawable.line,
        "linkedin" to R.drawable.linkedin,
        "lyft" to R.drawable.lyft,
        "medium" to R.drawable.medium,
        "outlook" to R.drawable.microsoft,
        "microsoft" to R.drawable.microsoft,
        "myntra" to R.drawable.myntra,
        "netflix" to R.drawable.netflix,
        "notion" to R.drawable.notion,
        "paypal" to R.drawable.paypal,
        "pinterest" to R.drawable.pinterest,
        "reddit" to R.drawable.reddit,
        "shopify" to R.drawable.shopify,
        "skype" to R.drawable.skype,
        "slack" to R.drawable.slack,
        "snapchat" to R.drawable.snapchat,
        "soundcloud" to R.drawable.soundcloud,
        "spotify" to R.drawable.spotify,
        "steam" to R.drawable.steam,
        "tiktok" to R.drawable.tiktok,
        "tinder" to R.drawable.tinder,
        "tumblr" to R.drawable.tumblr,
        "twitch" to R.drawable.twitch,
        "twitter" to R.drawable.twitter,
        "uber" to R.drawable.uber,
        "udemy" to R.drawable.udemy,
        "unsplash" to R.drawable.unsplash,
        "waze" to R.drawable.waze,
        "website" to R.drawable.website,
        "wechat" to R.drawable.wechat,
        "wikipedia" to R.drawable.wikipedia,
        "wish" to R.drawable.wish,
        "wordpress" to R.drawable.wordpress,
        "yahoo" to R.drawable.yahoo,
        "zomato" to R.drawable.zomato,
        "zoom" to R.drawable.zoom,
    )
}